### ISSUE TITLE
Excelente!!!

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/f-m3-evaluacion-intermedia-m-m-e#1]
Buen trabajo @m-m-e !

Si te animas, intenta esto:

1. Mover el array de pokemons a otro archivo e importarlo en App.
2. Inicializar el estado de App con el array de pokemons y utilizar este en lugar de la constante `pokemon`.
3. Añadir un click a Pokemon que: marca o desmarca el pokemon como favorito en el array del estado de App.
4. Pasar este dato al componente Pokemon por props
5. Pintar Pokemon con otros estilos cuando por props nos llegue la info de que el pokemon es favorito

Si tienes cualquier duda, avisa!

Al turrón

**Comment by m-m-e** [comment]
Thanks @oneeyedman :+1:  I've made the improvements you suggested, let me know what you think!

**Comment by oneeyedman** [comment]
Muy bien hecho, @m-m-e!!! Super buen trabajo y super buena pinta!!!
